name:                SubsetL
version:             0.1.0.0
github:              "Weheineman/SubsetL"
license:             BSD3
author:              "Gianni Weinand"
maintainer:          "example@example.com"
copyright:           "2019 Gianni Weinand"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Weheineman/SubsetL#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5.11
- array

library:
  source-dirs: src

executables:
  SubsetL-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SubsetL

tests:
  SubsetL-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SubsetL
